/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AutoRecordPanel: typeof import('./src/components/common/AutoRecordPanel.vue')['default']
    BusStopTimeline: typeof import('./src/components/common/BusStopTimeline.vue')['default']
    ETAIndicator: typeof import('./src/components/common/ETAIndicator.vue')['default']
    MapLegend: typeof import('./src/components/map/MapLegend.vue')['default']
    OfflineBanner: typeof import('./src/components/common/OfflineBanner.vue')['default']
    RouteBadge: typeof import('./src/components/common/RouteBadge.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StopInfoPanel: typeof import('./src/components/map/StopInfoPanel.vue')['default']
    TabBar: typeof import('./src/components/layout/TabBar.vue')['default']
    TimeOverride: typeof import('./src/components/dev/TimeOverride.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanButton: typeof import('vant/es')['Button']
    VanDropdownItem: typeof import('vant/es')['DropdownItem']
    VanDropdownMenu: typeof import('vant/es')['DropdownMenu']
    VanIcon: typeof import('vant/es')['Icon']
    VanLoading: typeof import('vant/es')['Loading']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanSearch: typeof import('vant/es')['Search']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTag: typeof import('vant/es')['Tag']
  }
}
